{
 "title": "Benchmark",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Restful_URL",
    "label": "Restful URL",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"name\" WHERE \"name\" =~ /ReqType=1/"
   },
   {
    "name": "gRPC_URL",
    "label": "gRPC URL",
    "query": "SHOW TAG VALUES FROM \"grpc_req_duration\" WITH KEY = \"name\" WHERE \"name\" =~ /ReqType=2/"
   },
   {
    "name": "gRPC_Stream_URL",
    "label": "gRPC Stream URL",
    "query": "SHOW TAG VALUES FROM \"grpc_req_duration\" WITH KEY = \"name\" WHERE \"name\" =~ /ReqType=3/"
   }
  ]
 },
 "panels": [
  { "title": "Restful (1)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration (1)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "select mean(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 from \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Request (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"url\") FROM \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Duration (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select sum(\"value\") from \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Request / Second (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select count(\"value\") / (sum(\"value\") / 1000) from \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Total Client (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select first(\"value\") FROM \"vus\"  where \"name\" =~ /^$Restful_URL$/ AND \"name\" =~ /ReqType=1/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Received (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Data Received / Second (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from \n(select sum(\"value\") from \"data_received\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Received / Request (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Sent (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Data Sent / Second (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from \n(select sum(\"value\") from \"data_sent\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"http_req_duration\" WHERE (\"name\" =~ /^$Restful_URL$/) AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Sent / Request (1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$Restful_URL$/) AND \"name\" =~ /ReqType=1/ AND $timeFilter"
    }
   ]
  },
  { "title": "gRPC (2)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request Duration (2)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "select mean(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Request (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"url\") FROM \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Duration (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select sum(\"value\") from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Request / Second (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select count(\"value\") / (sum(\"value\") / 1000) from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Total Client (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select first(\"value\") FROM \"vus\"  where \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Received (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_received",
     "query": "SELECT sum(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Received / Second (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from \n(select sum(\"value\") from \"data_received\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Received / Request (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Sent (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_received",
     "query": "SELECT sum(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Sent / Second (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from \n(select sum(\"value\") from \"data_sent\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Sent / Request (2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$gRPC_URL$/) AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    }
   ]
  },
  { "title": "gRPC Stream (3)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request Duration (3)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "select mean(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 90) as p90, percentile(\"value\", 95) as p95 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Request (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"url\") FROM \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Duration (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select sum(\"value\") from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Request / Second (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iterations",
     "query": "select count(\"value\") / (sum(\"value\") / 1000) from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    }
   ]
  },
  {
   "title": "Total Client (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select first(\"value\") FROM \"vus\"  where \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Received (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Data Received / Second (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from\n(select sum(\"value\") from \"data_received\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Received / Request (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_received\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Data Sent (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "Data Sent / Second (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select * from\n(select sum(\"value\") from \"data_sent\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter),\n(select sum(\"value\") / 1000 from \"grpc_req_duration\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter)"
    }
   ]
  },
  {
   "title": "Data Sent / Request (3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"data_sent\" WHERE (\"name\" =~ /^$gRPC_Stream_URL$/) AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  },
  { "title": "vs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Request Durations",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Restful.Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Restful_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=1/" }
     ]
    },
    {
     "alias": "gRPC.Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "query": "SELECT mean(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$gRPC_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=2/" }
     ]
    },
    {
     "alias": "gRPC Stream.Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grpc_req_duration",
     "query": "SELECT mean(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$gRPC_Stream_URL$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/RequestType=3/" }
     ]
    },
    {
     "alias": "Restful.Min",
     "query": "SELECT min(\"value\") FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter"
    },
    {
     "alias": "gRPC.Min",
     "query": "SELECT min(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    },
    {
     "alias": "gRPC Stream.Min",
     "query": "SELECT min(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    },
    {
     "alias": "Restful.Median",
     "query": "SELECT median(\"value\") FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter"
    },
    {
     "alias": "gRPC.Median",
     "query": "SELECT median(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    },
    {
     "alias": "gRPC Stream.Median",
     "query": "SELECT median(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    },
    {
     "alias": "Restful.Max",
     "query": "SELECT max(\"value\") FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter"
    },
    {
     "alias": "gRPC.Max",
     "query": "SELECT max(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    },
    {
     "alias": "gRPC Stream.Max",
     "query": "SELECT max(\"value\") FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    },
    {
     "alias": "Restful.P90",
     "query": "SELECT percentile(\"value\", 90) FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter"
    },
    {
     "alias": "gRPC.P90",
     "query": "SELECT percentile(\"value\", 90) FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    },
    {
     "alias": "gRPC Stream.P90",
     "query": "SELECT percentile(\"value\", 90) FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    },
    {
     "alias": "Restful.P95",
     "query": "SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE \"name\" =~ /^$Restful_URL$/ AND $timeFilter"
    },
    {
     "alias": "gRPC.P95",
     "query": "SELECT percentile(\"value\", 95) FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_URL$/ AND \"name\" =~ /ReqType=2/ AND $timeFilter"
    },
    {
     "alias": "gRPC Stream.P95",
     "query": "SELECT percentile(\"value\", 95) FROM \"grpc_req_duration\" WHERE \"name\" =~ /^$gRPC_Stream_URL$/ AND \"name\" =~ /ReqType=3/ AND $timeFilter"
    }
   ]
  }
 ]
}